"""Add options field to User

Revision ID: 280f8be1b97f
Revises: 42a538797247
Create Date: 2023-01-30 14:59:58.199614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '280f8be1b97f'
down_revision = '42a538797247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_users_options'), 'users', ['options'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_options'), table_name='users')
    op.drop_column('users', 'options')
    # ### end Alembic commands ###
