"""Options field default

Revision ID: ae2aef545028
Revises: 280f8be1b97f
Create Date: 2023-01-30 15:01:05.329355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2aef545028'
down_revision = '280f8be1b97f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
