"""Change ids fields type to BigInt

Revision ID: b12995b2166d
Revises: ae2aef545028
Create Date: 2023-01-31 03:38:44.542089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b12995b2166d'
down_revision = 'ae2aef545028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
